### ISSUE TITLE
Support for @container

### ISSUE THREAD

**Issue by stijnvanderlaan** [thysultan/stylis#303]
Chrome 105 shipped with support for container query, would be great if this would be supported.
Example:
```css
@container (max-width: 300px) {
  .element {
    display: none;
  }
}
```
