### ISSUE TITLE
minification does not happen for gradients

### ISSUE THREAD

**Issue by layershifter** [thysultan/stylis#306]
### Versions

`stylis@4.1.3`

### Problem

Stylis does minification and it works great:

```css
.foo { color: red; }
.bar {
  color: blue;
  background: orange;
}
/* ⬇️⬇️⬇️ */
.foo{color:red;}.bar{color:blue;background:orange;}
```

The problem happens with `radial-gradient`& `repeating-linear-gradient`:

```css
.foo {
  background: repeating-linear-gradient(
    -45deg,
    red,
    red 5px,
    blue 5px,
    blue 10px
  );
}
.bar {
  color: blue;
  background: orange;
}
.baz {
  background-image:radial-gradient(
    ellipse 50rem 50rem,
    #8e91e6 0%, 
    #403f5a 25%,
    transparent 46%
  )
}
/* ⬇️⬇️⬇️ */
 .foo{background:repeating-linear-gradient(
    -45deg,
    red,
    red 5px,
    blue 5px,
    blue 10px
  );}.bar{color:blue;background:orange;}.baz{background-image:radial-gradient(
    ellipse 50rem 50rem,
    #8e91e6 0%, 
    #403f5a 25%,
    transparent 46%
  );}
```

👆 notice that `.foo` & `.baz` are not minified.

### Reproduction

https://codesandbox.io/s/awesome-rgb-wf0j3e
