### ISSUE TITLE
Comments in pseudo-selector arguments are parsed as part of the value

### ISSUE THREAD

**Issue by Andarist** [thysultan/stylis#310]
```css
tr:not(:first-child/* comm */) {
  border-top-width: 1px;
}
```

**Actual**: this comment becomes part of the `element.value`
**Expected**: it shouldn't be part of the `element.value` and it should create a comment node
