### ISSUE TITLE
Support for @layer blocks

### ISSUE THREAD

**Issue by probablyup** [thysultan/stylis#312]
Hey friends! [This issue](https://github.com/styled-components/styled-components/issues/3950) was opened over on styled-components and I wasn’t sure if additional work was needed to support the syntax?

Reference:

```ts
compile(`
  div {
    @media screen {
      color: red;
    }
    
    @layer base {
      color: blue;
    }
  }
`.trim())
```

Expected:

```css
@media screen {
  [namespace] div {
    color: red;
  }
}

@layer base {
  [namespace] div {
    color: blue;
  }
}
```

Received:

```css
@media screen {
  [namespace] div {
    color: red;
  }
}

@layer base {
  color: blue;
}
```
