### ISSUE TITLE
Pseudoselectors without & prefix emit malformed CSS

### ISSUE THREAD

**Issue by quantizor** [thysultan/stylis#323]
```css
div {
  :hover {
    color: red;
  }
}
```

The above code used to work in stylis v3, but it seems since stylis v4 an ampersand is explicitly required, e.g.

```css
div {
  &:hover {
    color: red;
  }
}
```

Can the prior functionality to pretend an `&` is there for a leading `:` be restored?
