### ISSUE TITLE
Fix support for @property houdini syntax

### ISSUE THREAD

**Issue by quantizor** [thysultan/stylis#324]
For example [from MDN]():

```css
@property --item-size {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}
```

Currently stylis seems to mess with the `<>` characters inside the `syntax` rule:

```css
@property --item-size {
  syntax: "";
  inherits: true;
  initial-value: 40%;
}
```

**Comment by Andarist** [comment]
Are those already stable features? either way... this doesn't work and the fix for it should automatically fix this within `@property`:
```css
::after {
  content: "<stuff>";
}
```
