### ISSUE TITLE
Better leave `&` as original code when there's no CSS Selector

### ISSUE THREAD

**Issue by nitipit** [thysultan/stylis#326]
# Issue
When using `&` and there's no CSS Selector, the `&` has been removed in the compiled code.
Since **nesting CSS** `&` becomes official in early 2023, It would be better not to remove it.

## Input
```css
&.red { background-color: red }
```
## Compiled to 
```css
.red { background-color: red }
```

# Expect
## Input
```css
&.red { background-color: red }
```
## Compiled to 
```css
&.red { background-color: red }
```
