### ISSUE TITLE
Break of root `&` selector

### ISSUE THREAD

**Issue by zombieJ** [thysultan/stylis#333]
PR https://github.com/thysultan/stylis/commit/cd6750d8d91b2e79ff8a935acc9a0620885e2830 support the feature that not convert `&` when at root. But this breaks the usage case that create a help util to be nest case:

```tsx
const sampleUtilStyle = `& a { color: red; }`;  // Just a sample

// This can be reused in both root and nest case for origin:
const rootStyle = `${sampleUtilStyle}`; // since `&` at root is not valid in css spec which will be break
const nestStyle = `.cls { ${sampleUtilStyle} }`;
```

I'm not sure support `nesting CSS spec` in stylis is a good idea since we use stylis is to handle the case that not support nest css.

ref issue: https://github.com/ant-design/ant-design/issues/50533

**Comment by elrrrrrrr** [comment]
I have encountered a similar issue and hope to get a definite answer. 
Thanks 🙏🏻

**Comment by Andarist** [comment]
It's not clear to me how it broke. Please include a repro that involves calling stylis APIs

**Comment by zombieJ** [comment]
### 4.3.3

https://stackblitz.com/edit/react-sxn6wd?file=package.json,demo.tsx

<img width="291" alt="截屏2024-08-22 17 44 06" src="https://github.com/user-attachments/assets/7db501f5-711d-42e8-a7fc-90fc44a6b382">

### 4.3.2

https://stackblitz.com/edit/react-sxn6wd-kuzwkb?file=package.json,demo.tsx

<img width="281" alt="截屏2024-08-22 17 43 58" src="https://github.com/user-attachments/assets/b13da28b-8097-42eb-a140-ba15c2b6a1a1">

**Comment by Andarist** [comment]
Note that `&` is not invalid in CSS, it represents the current scoping root if it's not used in a nested rule.

Tbh, it feels to me that you were relying on a very implicit pattern that relied on implementation details of the previous Stylis versions removing those root `&`. It wasn't a well-defined behavior.

**Comment by zombieJ** [comment]
> Note that & is not invalid in CSS...

`&` is to be follow parent selector in prev version. I'm not sure escape it as `&` in root is a good way. As above mentioned, stylis is the CSS Preprocessor which help to convert nest style into flatten and fill prefix for browser compatible. So keep the `&` in root to support nest case is not what it should do since it will be unclear of the `&` definition.

```less
a {
  &:hover { // should this keep as `&` to trade as native nest css?
    color: red;
  }
}
```

Should be:

```css
a:hover { color: red; }
```

or:

```css
/** Just keep as nest css since I want to let stylis not to process this part */
a {
  &:hover {
    color: red;
  }
}
```

If we want to support `&` escape, maybe add a new feature like `~&` instead of auto detect:

```less
a {
  ~&:hover { // Tell stylis keep the sctructure
    color: red;
  }
}
```
