### ISSUE TITLE
`@namespace` at-rule gets omitted

### ISSUE THREAD

**Issue by neet** [thysultan/stylis#343]
Hi, thank you for maintaining an awesome project.

While I'm trying to use [CSS `@namespace`](https://developer.mozilla.org/ja/docs/Web/CSS/@namespace) feature, I'm having trouble with the at-rule always gets omitted.

Consider the following input, which I borrowed from an MDN article.

```js
import { compile, serialize, stringify } from 'stylis'

const css = `
@namespace svg url('http://www.w3.org/2000/svg');

a {
  color: orangered;
  text-decoration: underline dashed;
  font-weight: bold;
}

svg|a {
  fill: blueviolet;
  text-decoration: underline solid;
  text-transform: uppercase;
}
`

console.log(serialize(compile(css), stringify))
```

We get the following CSS as an output. Note that it lacks the `@namespace` rule.

```css
a{color:orangered;text-decoration:underline dashed;font-weight:bold;}svg|a{fill:blueviolet;text-decoration:underline solid;text-transform:uppercase;}
```

You can see the full reproducible code from the repository below.
https://github.com/neetlab/stylis-namespace-omitted
